Add in app update
revanced/revanced-manager-compose pull request #25
Opened 2023-05-22 20:07 UTC by Aunali321

Currently auto downloads latest manager version when entering update screen.

2023-05-22 20:41 UTC, Axelen123 requested changes

2023-05-22 20:41 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/compose/ui/screen/SettingsScreen.kt
> +                getViewModel<UpdateSettingsViewModel>()
```suggestion
```
You don't need to `getViewModel()` here because it is already defined as a default parameter here:
https://github.com/revanced/revanced-manager-compose/blob/fc649882f9580639db160f26cbe229c7de885888/app/src/main/java/app/revanced/manager/compose/ui/screen/settings/UpdatesSettingsScreen.kt#L148

2023-05-22 20:41 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/compose/ui/screen/settings/UpdatesSettingsScreen.kt
> +                text = "This update adds many functionality and fixes many issues in Manager. New experiment toggles are also added, they can be found in Settings > Advanced. Please submit some feedb
You can use a string resource

2023-05-22 20:47 UTC, Aunali321 commented on app/src/main/java/app/revanced/manager/compose/ui/screen/settings/UpdatesSettingsScreen.kt
> +                text = "This update adds many functionality and fixes many issues in Manager. New experiment toggles are also added, they can be found in Settings > Advanced. Please submit some feedb
this is only temporary. will be replace by actual changelog

2023-05-23 06:57 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/compose/ui/screen/settings/UpdatesSettingsScreen.kt
> +                text = "This update adds many functionality and fixes many issues in Manager. New experiment toggles are also added, they can be found in Settings > Advanced. Please submit some feedb
Oh. That makes sense.

2023-05-23 09:02 UTC, merged