Contributors page
revanced/revanced-manager-compose pull request #42
Opened 2023-06-23 14:54 UTC by Tyffhabwe

- https://github.com/revanced/revanced-manager-compose/issues/34
- Finally got over all those build issues oml
-

2023-06-26 09:56 UTC, CnC-Robert requested changes

2023-06-26 09:56 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/ContributorScreenViewModel.kt
> +        }
Don't run this on ui thread, do it like the old [ContributorsViewModel](https://github.com/revanced/revanced-manager-compose-old/blob/main/app/src/main/java/app/revanced/manager/ui/viewmodel/ContributorsViewModel.kt) instead

2023-06-26 09:56 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/ContributorScreenViewModel.kt
> +class ContributorScreenViewModel(private val repository: ReVancedRepository): ViewModel() {
Rename to `ContributorViewModel`

2023-06-26 09:56 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +    viewModel: ContributorScreenViewModel
You should use `getViewModel()` here instead of in `MainActivity`

2023-06-26 09:56 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/SettingsScreen.kt
> +                navController = navController
Instead of passing down the `navController`, use a callback like `onBackClick`

2023-06-26 09:56 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +}
It might be better to just save the names as separate strings

2023-06-26 09:56 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +            if (expanded) {
Maybe it's better to always show the contributors instead of making it expandable

2023-06-26 09:56 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +                .height(IntrinsicSize.Max)
Use `fillMaxHeight()` or `fillMaxSize()`

2023-06-26 10:04 UTC, Axelen123 requested changes

2023-06-26 10:04 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +                            }
[ArrowButton](https://github.com/revanced/revanced-manager-compose/blob/dev/app/src/main/java/app/revanced/manager/ui/component/ArrowButton.kt) can be used here

2023-06-26 10:35 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +                .height(IntrinsicSize.Max)
I am guessing it may have been used due to issues with nesting scrolling

2023-06-26 12:41 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +                .height(IntrinsicSize.Max)
> I am guessing it may have been used due to issues with nesting scrolling

Yeah it was

2023-06-26 12:43 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +}
> It might be better to just save the names as separate strings

Won't that mean that if we get new repositories that we have to come back and add them?

2023-06-26 15:53 UTC, Ushie commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +}
> It might be better to just save the names as separate strings

That's not true, changing the API should also change the contributors and things like that, by using strings you essentially hardcoded the repositories here

2023-06-26 15:54 UTC, Ushie commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +            if (expanded) {
Its expanded by default, this would act the same as https://revanced.app/contributors

2023-06-27 11:12 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/viewmodel/ContributorScreenViewModel.kt
> +        }
Done!

2023-06-27 11:12 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/viewmodel/ContributorScreenViewModel.kt
> +class ContributorScreenViewModel(private val repository: ReVancedRepository): ViewModel() {
Done!

2023-06-27 11:12 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +    viewModel: ContributorScreenViewModel
Done!

2023-06-27 11:12 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/SettingsScreen.kt
> +                navController = navController
Done!

2023-06-27 11:45 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +                            }
Done!

2023-06-27 11:50 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +            if (expanded) {
then why make the cards collapsable in the first place

2023-06-27 11:54 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/ContributorScreen.kt
> +}
alright but it should keep the ReVanced in the name

2023-06-28 15:04 UTC, Axelen123 approved these changes

2023-06-28 15:07 UTC, Axelen123 reviewed
Removing these because they are unused

2023-06-28 19:47 UTC, CnC-Robert approved these changes

2023-06-28 19:51 UTC, merged