feat: app downloader
revanced/revanced-manager-compose pull request #43
Opened 2023-06-24 19:21 UTC by CnC-Robert

2023-06-26 11:30 UTC, Axelen123 requested changes

2023-06-26 11:30 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/downloader/APKMirror.kt
> +        }
can you move this to `HttpService` so it can be reused?

2023-06-26 11:30 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/downloader/APKMirror.kt
> +)
JSON classes belong in `network/dto`

2023-06-26 11:30 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/downloader/APKMirror.kt
> +    val `signatures-sha256`: List<String>,
Use the `@SerialName` annotation so we don't need `-` in the name

2023-06-26 11:30 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppDownloaderViewModel.kt
> +            )
Maybe use `withContext(Dispatchers.IO)` in here so you don't have to copy `uiSafe`?

I should probably fix the `uiSafe` function to prevent crashing when run on another thread, but this seems like the easiest way to avoid the issue for now.

2023-06-28 20:11 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppDownloaderViewModel.kt
> +        }
`PM` uses .collect() while the ViewModel uses .first()

2023-06-29 11:45 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppDownloaderViewModel.kt
> +        }
The ViewModel loads the amount of patches that support each version while `PM` loads the amount patches that support each application

2023-06-30 17:16 UTC, Axelen123 requested changes

2023-06-30 17:16 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppDownloaderViewModel.kt
> +                    onComplete(apkInfo)
This `onComplete` might belong to a destroyed composition if you rotate the screen before the download finishes.

I believe this can be solved by creating a `var` on the viewmodel and then using a [SideEffect](https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary#SideEffect(kotlin.Function0)) to set the variable. That variable does not have to be compose state.

Example:
```kt
@Composable
fun DownloadScreen(onComplete: (AppInfo) -> Unit, vm: TheViewModel) {
     SideEffect {
           vm.onDownloadComplete = onComplete
     }
}

2023-06-30 17:16 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +    BackHandler(onBack = onBackClick)
Why was this added?

2023-06-30 17:47 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +    BackHandler(onBack = onBackClick)
It sets the behavior for the system back button

2023-06-30 17:51 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/data/room/Converters.kt
> +    fun fileFromString(value: String) = File(value)
Won't the string be the absolute path anyway?

2023-06-30 18:31 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +    BackHandler(onBack = onBackClick)
Doesn't reimagined or `Scaffold` do this for us?

2023-07-01 12:20 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +    BackHandler(onBack = onBackClick)
No it just runs `pop()` if you dont set it

2023-07-01 12:22 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/network/downloader/APKMirror.kt
> +        _downloadProgress.emit(null)
Does that run after `throw e`?

2023-07-01 12:27 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/PatchesSelectorScreen.kt
> +    BackHandler(onBack = onBackClick)
Looks like you changed the provided `onBackClick`. Now it makes sense

2023-07-01 12:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/downloader/APKMirror.kt
> +        _downloadProgress.emit(null)
It always runs even if the `try` block fails. You can look up whta `finally` does

2023-07-01 14:05 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/network/downloader/AppDownloader.kt
> +    abstract suspend fun getAvailableVersionList(apk: String, versionFilter: Set<String>)
fixed

2023-07-01 14:07 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/DownloadsViewModel.kt
> +    val selection = mutableStateListOf<DownloadedApp>()
what difference does that make?

2023-07-01 14:20 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/DownloadsViewModel.kt
> +    val selection = mutableStateListOf<DownloadedApp>()
> What difference does that make?

Sets can be searched through more efficiently and there is no risk at all of duplicates.

2023-07-02 11:56 UTC, Axelen123 requested changes

2023-07-02 11:56 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/DownloadsViewModel.kt
> +class DownloadsViewModel(
Shouldn't this be called `DownloadsSettingsViewModel` since it belongs to `DownloadsSettingsScreen`?

2023-07-02 11:56 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppDownloaderViewModel.kt
> +            bundle.value.patches.flatMap { patch ->
```suggestion
        bundles.flatMap { (_, bundle) ->
            bundle.patches.flatMap { patch ->
```

2023-07-02 11:56 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
> +            )
Move [this](https://github.com/revanced/revanced-manager-compose/blob/dev/app/src/main/java/app/revanced/manager/ui/screen/settings/GeneralSettingsScreen.kt#L128) to `ui/components/settings`, rename it to `BooleanPreference` and make it public so we can use it here as well.

2023-07-02 11:56 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/downloader/APKMirror.kt
> +                client.download(saveLocation) {
Use a `val` here instead. Also, the thing you called `.let` on does not appear to be used.

2023-07-02 11:56 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/downloader/APKMirror.kt
> +                                    versions[version] = link
I think its better to use a `flow { }` block that emits `Pair<String, String>` (`emit(version to link)`) instead of emitting a map to a stateflow. We can use `.collect` in the viewmodel with its `viewModelScope` and add all emitted key-value pairs to a `mutableStateMapOf()`.
The viewmodel can also do the filtering using the `.filter` operator so we don't have to implement filtering in every single downloader

2023-07-02 11:56 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/AppSelectorScreen.kt
> +                } ?: context.toast(context.getString(R.string.failed_to_load_apk))
```suggestion
                vm.loadSelectedFile(apkUri)?.let(onAppClick) ?: 
                       context.toast(context.getString(R.string.failed_to_load_apk))
```

2023-07-11 09:36 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/DownloadsViewModel.kt
> +class DownloadsViewModel(
Then it's better to rename every settings ViewModel

2023-07-12 21:39 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
> +            )
Is there really a point in doing that? since you still have to pass the same amount of parameters to the function.

2023-07-13 09:43 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
> +            )
> Is there really a point in doing that? since you still have to pass the same amount of parameters to the function.

Yes, but those parameters don't require as much code to create.

2023-07-13 19:42 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
> +            )
> > Is there really a point in doing that? since you still have to pass the same amount of parameters to the function.
> 
> Yes, but those parameters don't require as much code to create.

Nah you still need `enabled = someVar` and `onSwitch = { someVar = !someVar }`

2023-07-13 19:53 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
> +            )
You don't need `Text` though. You won't even need the lambdas after I merge one of my local branches (which I have not done yet so you don't have to deal with conflicts on this branch).

2023-07-13 22:17 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
> +            )
Wdym you don't need `text`?

2023-07-13 22:43 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/DownloadsSettingsScreen.kt
> +            )
you only need to specify a string resource instead of a lambda. keep it as-is if you want. I'll have to change that code anyway

2023-07-14 08:35 UTC, Axelen123 requested changes

2023-07-14 08:35 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/downloader/AppDownloader.kt
> +     * @param preferUniversal Whether it should prefer an universal or an arch-specific apk.
This parameter does not exist anymore
```suggestion
```

2023-07-14 08:54 UTC, Axelen123 approved these changes

2023-07-14 08:54 UTC, merged