feat/bundle info screens
ReVanced/revanced-manager-compose pull request #55
Opened 2023-07-10 12:48 UTC by Tyffhabwe

- Not a full PR yet. Still got some stuff to work on just want early feedback before I go too deep

2023-07-10 17:51 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundlePatchesDialog.kt
> +                        }
The figma makes heavy use of this. Can you turn it into a composable function?

2023-07-10 17:51 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/SourcesScreen.kt
> +            },
Don't we always want `Icons.Default.Close` since it is a dialog?

2023-07-12 09:41 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +                ) {
I tried that when I originally designed this Composable but ran into issues because of passing through mutableState variables as method arguments that made stuff like writing the Switch and input fields difficult

2023-07-13 01:12 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundlePatchesDialog.kt
> +                        }
Done!

2023-07-13 01:17 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/SourcesScreen.kt
> +            },
Done!

2023-07-13 10:43 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundlePatchesDialog.kt
> +    action: @Composable () -> Unit
Can you rename this parameter to `content` and move the function to `ui/component`?

2023-07-13 10:45 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/SourcesScreen.kt
> +            topBarTitle = stringResource(R.string.import_bundle),
Same here. This is always going to be `R.string.import_bundle`

2023-07-13 10:49 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +                ) {
You usually give the composable the current value and a callback function that can change the value. This is called [state hoisting](https://developer.android.com/jetpack/compose/state#state-hoisting).

If you run into any problems, let me know and I will help you

2023-07-14 08:01 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundlePatchesDialog.kt
> +    action: @Composable () -> Unit
Done

2023-07-14 08:03 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/SourcesScreen.kt
> +            topBarTitle = stringResource(R.string.import_bundle),
Done!

2023-07-16 04:27 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +                ) {
Done!

2023-07-17 12:09 UTC, Axelen123 requested changes

2023-07-17 12:09 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +                                "Delete"
Can you use string resources so this screen can be translated?

Placeholders such as the version number do not need string resources

2023-07-17 12:09 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundlePatchesDialog.kt
> +            ) {
Bundles can have hundreds of patches. Can you switch to a `LazyColumn` here?

2023-07-20 02:39 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/AppScaffold.kt
> +fun BundleTopBar(
Done!

2023-07-20 02:40 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +            }
Done!

2023-07-20 03:08 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +    else "$patchCount Patches available, tap to view"
done!

2023-07-20 03:25 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +                                "Delete"
Done!

2023-07-20 03:26 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundleInformationDialog.kt
> +fun BundleInfoContent(
Done!

2023-07-20 03:58 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/BundlePatchesDialog.kt
> +            ) {
Done!

2023-07-20 03:59 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/sources/ImportBundleDialog.kt
> +    val integrationText = if (integrations == null) "" else integrations.toString()
Done!

2023-07-21 12:33 UTC, Axelen123 requested changes
Looks better now.

There are still some hardcoded non-placeholder strings that should be replaced with string resources.

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/sources/RemoteSource.kt
> +    constructor(name: String, id: Int, directory: File) : this(name, Url("Unknown"), id, directory)
It is possible to get the Url from the database by editing the `when` block found [here](https://github.com/ReVanced/revanced-manager-compose/blob/d3ba0af06a15ef8bcadaf0b23eb94f66e162f16a/app/src/main/java/app/revanced/manager/domain/repository/SourceRepository.kt#L42), so this should not be needed

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +    var viewBundleDialogPage by remember { mutableStateOf(false) }
This should be `rememberSaveable` instead of `remember` so the state is not lost when rotating the screen.

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +            topBarTitle = stringResource(R.string.bundle_information),
Aren't these two parameters always the same?

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +            remoteName = remoteName,
Can't you retrieve these two inside of `BundleInformationDialog` since you are passing down the source anyway?

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundleTextContent.kt
> +        }
Can you move this to `ImportBundleDialog` since it only appears there?

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/res/values/strings.xml
> +    <string name="Patches_available_tap_to_view">%d Patches available, tap to view</string>
Can you give these a name that is either shorter or refers to the context/location in which the strings appear?

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +package app.revanced.manager.ui.component
The `LocalSourceItem` and `RemoteSourceItem` functions in this file are unused and should be removed

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +            ) {
Is this `Column` truly necessary?

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                ) {
This should be vertically scrollable

2023-07-21 12:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                                        text = patch.description,
```suggestion
                                patch.description?.let {
                                    Text(
                                        text = it,
```

2023-07-23 12:48 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +package app.revanced.manager.ui.component
Done!

2023-07-23 12:49 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +    var viewBundleDialogPage by remember { mutableStateOf(false) }
Done!

2023-07-23 12:52 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +            topBarTitle = stringResource(R.string.bundle_information),
onBackIcon is used twice by both the BundlePatchesDialog and BundleInformationDialog so would it not make sense to keep it as a variable?

2023-07-23 13:01 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +            remoteName = remoteName,
we need to have access to patchCount at this level to display the sources correctly, so I simply use existing patchCount var and pass through what is needed inside BundleInformationDialog

2023-07-23 13:09 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +            ) {
done!

2023-07-23 13:30 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                ) {
done!

2023-07-23 13:32 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                                        text = patch.description,
done!

2023-07-23 13:39 UTC, Tyffhabwe commented on app/src/main/res/values/strings.xml
> +    <string name="Patches_available_tap_to_view">%d Patches available, tap to view</string>
done!

2023-07-23 13:50 UTC, Axelen123 requested changes

2023-07-23 13:50 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/ImportBundleDialog.kt
> +fun BundleInfoListItem(
Can you move this to its own file?

2023-07-23 13:52 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/domain/sources/RemoteSource.kt
> +    constructor(name: String, id: Int, directory: File) : this(name, Url("Unknown"), id, directory)
done!

2023-07-23 13:53 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundleTextContent.kt
> +        }
done!

2023-07-23 13:53 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/ImportBundleDialog.kt
> +fun BundleInfoListItem(
done!

2023-07-23 14:28 UTC, Axelen123 requested changes

2023-07-23 14:28 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundleInfoContent.kt
> +        text = "Information",
Should be a string resource

2023-07-23 14:28 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                            text = "Tap on the patches to get more information about them"
Should be a string resource

2023-07-23 14:28 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +            },
This needs a content description for screen readers because it is not purely for decoration. Something like `back` will do.

It has to be a string resource too.

I am still not sure why this is a parameter since dialogs always use `ArrowBack`.

2023-07-23 14:28 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                                    contentDescription = null,
This also needs a content description for screen readers. `close` will do

2023-07-23 14:28 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/ImportBundleDialog.kt
> +                            contentDescription = null
This also needs a description. `close` or `cancel` will work

2023-07-23 14:28 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/ImportBundleDialog.kt
> +                                Text("Remote")
Use the string resources

2023-07-23 14:28 UTC, Axelen123 commented on app/src/main/res/values/strings.xml
> +    <string name="patches_available_d">%d Patches available, tap to view</string>
Remove `txt` and `d`

2023-07-23 14:32 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +            topBarTitle = stringResource(R.string.bundle_information),
The icon and title should be set by `BundleInformationDialog` and `BundleImportDialog` instead of the one calling them. It does not make sense to forward those

2023-07-23 14:35 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/SourceItem.kt
> +            },
done!

2023-07-23 14:37 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundleInfoContent.kt
> +        text = "Information",
done!

2023-07-23 14:38 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                            text = "Tap on the patches to get more information about them"
done!

2023-07-23 14:39 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundlePatchesDialog.kt
> +                                    contentDescription = null,
done!

2023-07-23 14:40 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/ImportBundleDialog.kt
> +                            contentDescription = null
done!

2023-07-23 14:42 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/ImportBundleDialog.kt
> +                                Text("Remote")
done!

2023-07-23 14:43 UTC, Tyffhabwe commented on app/src/main/res/values/strings.xml
> +    <string name="patches_available_d">%d Patches available, tap to view</string>
done!

2023-07-23 15:19 UTC, Axelen123 approved these changes

2023-07-23 15:27 UTC, merged