feat: improve accessibility
ReVanced/revanced-manager-compose pull request #64
Opened 2023-07-15 18:26 UTC by PatrykMis

* Label Back button
* Mark group section headings as headings

2023-07-15 20:31 UTC, CnC-Robert requested changes

2023-07-15 20:31 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/component/GroupHeader.kt
> +    modifier: Modifier = Modifier.semantics { heading() }
Default modifiers shouldn't be set like this since they will get overridden by anything that uses different modifiers.

Instead you should use `modifier = Modifier.semantics{}.then(modifier)` in the component that uses the modifier

2023-07-15 21:19 UTC, PatrykMis commented on app/src/main/java/app/revanced/manager/ui/component/GroupHeader.kt
> +    modifier: Modifier = Modifier.semantics { heading() }
Sorry, I don't understand how should I change this. I just did something that works and it's already tested, I'm not the experienced Kotlin developer.
Do you mean setting semantics for each heading one by one - e.g. in GeneralSettingsScreen.kt and related?

2023-07-15 21:26 UTC, PatrykMis commented on app/src/main/java/app/revanced/manager/ui/component/GroupHeader.kt
> +    modifier: Modifier = Modifier.semantics { heading() }
Anyway, I've tried what you've suggested and I have this error:
~~~BASH
e: file:///C:/revanced-manager-compose/app/src/main/java/app/revanced/manager/ui/component/GroupHeader.kt:15:64 Parameter 'modifier' is uninitialized here
~~~

2023-07-17 12:20 UTC, Axelen123 approved these changes

2023-07-17 12:20 UTC, merged