feat: finish implementing the sources system
ReVanced/revanced-manager-compose pull request #70
Opened 2023-07-28 11:28 UTC by Axelen123

Shows version info, adds auto updates, deals with errors better and remote sources now respect the provided URL.

2023-07-31 13:07 UTC, CnC-Robert requested changes

2023-07-31 13:07 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/network/api/ManagerAPI.kt
> +        operator fun Assets.component2() = find(ghIntegrations, ".apk")
These names are not clear.

2023-07-31 13:07 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt
> +private fun APIUrlDialog(currentUrl: String, onSubmit: (String?) -> Unit) {
Why not just use `onDismiss` here?

2023-07-31 13:07 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundleRepository.kt
> +    suspend fun onApiUrlChange() {
Wouldn't `reloadDefaultBundle` make more sense here?

2023-07-31 13:07 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AdvancedSettingsViewModel.kt
> +        patchBundleRepository.onApiUrlChange()
Can these 2 be called from different threads?

2023-07-31 14:32 UTC, Axelen123 commented on app/src/main/res/values/strings.xml
> +    <string name="api_url_dialog_warning">Never use an API that you do not trust.</string>
True

2023-07-31 14:33 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/ReVancedRepository.kt
> +    suspend fun getAssets(api: String? = null) = Assets(service.getAssets(api ?: prefs.api.get()).getOrThrow())
Yes. The parameter only exists because I have not implemented the bundle json format yet

2023-07-31 14:36 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundleRepository.kt
> +    }
The `load()` function is also called when you reset bundles

2023-07-31 14:37 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundleRepository.kt
> +            Log.d(tag, "Skipping update check because the network is unsafe.")
The `isSafe()` function returns true if you are connected to the internet and the network is unmetered.
I should probably change the log message though.

2023-07-31 14:41 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/bundles/BundleSource.kt
> +    protected val integrations = directory.resolve("integrations.apk")
Seems shorter to do it like this

2023-07-31 14:41 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/util/Util.kt
> +val BundleSource.isDefault get() = uid == 0
Because its an extension property

2023-07-31 14:42 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/PatchesSelectorViewModel.kt
> +                            // Filter out patches that don't exist.
Maybe, but that should be implemented in a different PR

2023-07-31 14:43 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +    }
The reason why this is done is because the floating action button is defined by the dashboard page

2023-07-31 14:45 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/BundlesScreen.kt
> +                coroutineScope = vm.viewModelScope
the scope returned by `rememberCoroutineScope` gets cancelled whenever the activity is destroyed, so it should only be used for things related to the composition (like animations or timers) and things that you expect to finish immediately.

The scope is used for updates, but it probably makes more sense to run `bundle.update()` in the viewmodel instead of passing down its scope.
I will do that

2023-07-31 14:46 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundlePersistenceRepository.kt
> +                versionInfo = VersionInfo("", ""),
Empty string indicates that there is no version. Either because the bundle is local or you haven't downloaded a remote bundle.

null probably makes more sense though, so I will switch to that.

2023-07-31 14:48 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/api/ManagerAPI.kt
> +        operator fun Assets.component2() = find(ghIntegrations, ".apk")
These are special `operator` functions for [destructuring](https://kotlinlang.org/docs/destructuring-declarations.html).

The functions allow me to destructure the `Assets` class just like a `Pair`

2023-07-31 14:48 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundleRepository.kt
> +    suspend fun onApiUrlChange() {
You are right. I will change

2023-07-31 14:48 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AdvancedSettingsViewModel.kt
> +        patchBundleRepository.onApiUrlChange()
`onApiUrlChange()` must run after the preference has been updated

2023-07-31 14:58 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AdvancedSettingsViewModel.kt
> +        patchBundleRepository.onApiUrlChange()
No i mean does this cause issues when you run this on a thread thats not main?

2023-07-31 14:59 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/BundlesScreen.kt
> +                coroutineScope = vm.viewModelScope
Done

2023-07-31 15:11 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt
> +private fun APIUrlDialog(currentUrl: String, onSubmit: (String?) -> Unit) {
A nullable parameter seems to work fine. Why?

2023-07-31 15:22 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundlePersistenceRepository.kt
> +                versionInfo = VersionInfo("", ""),
Done

2023-07-31 15:26 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundleRepository.kt
> +            Log.d(tag, "Skipping update check because the network is unsafe.")
Done

2023-07-31 15:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AdvancedSettingsViewModel.kt
> +        patchBundleRepository.onApiUrlChange()
They can be called on a different thread because DataStore prefs don't use compose state

2023-07-31 20:11 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/PatchesSelectorViewModel.kt
> +                            // Filter out patches that don't exist.
Alright

2023-07-31 20:12 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +    }
You can set the `showDialog` in the dashboard screen and pass it down to the screen along with a callback

2023-07-31 20:16 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/network/api/ManagerAPI.kt
> +        operator fun Assets.component2() = find(ghIntegrations, ".apk")
Seems a bit ugly to hardcode the filenames tho

2023-07-31 20:17 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt
> +private fun APIUrlDialog(currentUrl: String, onSubmit: (String?) -> Unit) {
Its less readable i guess

2023-07-31 20:17 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/domain/bundles/BundleSource.kt
> +    protected val integrations = directory.resolve("integrations.apk")
Seems a bit ugly to hardcode the filenames tho

2023-07-31 20:17 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundleRepository.kt
> +    }
Alright

2023-07-31 20:24 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/domain/repository/PatchBundleRepository.kt
> +            Log.d(tag, "Skipping update check because the network is unsafe.")
We should make it a preference at some point but for now it's fine

2023-08-01 18:56 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/bundles/BundleSource.kt
> +    protected val integrations = directory.resolve("integrations.apk")
We would still be hardcoding even if we moved them

2023-08-01 18:59 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BaseBundleDialog.kt
> +inline fun BaseBundleDialog(
This composable is large because its more of a template rather than a standalone component. Having it inline is not strictly needed but may reduce the amount of things we have to recompose

2023-08-01 19:04 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +    }
That is possible but I am not sure if there is much benefit in doing so. We kinda need the viewmodel anyway for calculating the amount of patches available, which is used by the fab while in the apps tab to determine if we should proceed to the app selector or go to the bundles tab

2023-08-01 19:06 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt
> +private fun APIUrlDialog(currentUrl: String, onSubmit: (String?) -> Unit) {
It makes the function easier to use because you don't have to close the dialog in multiple callbacks

```kt
            var showApiUrlDialog by rememberSaveable { mutableStateOf(false) }

            if (showApiUrlDialog) {
                APIUrlDialog(apiUrl) {
                    showApiUrlDialog = false
                    it?.let(vm::setApiUrl)
                }
            }
```

2023-08-01 20:47 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/ReVancedRepository.kt
> +    suspend fun getAssets(api: String? = null) = Assets(service.getAssets(api ?: prefs.api.get()).getOrThrow())
The json format has been implemented, so the parameter is no longer needed.

2023-08-02 15:09 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/network/api/ManagerAPI.kt
> +        operator fun Assets.component2() = find(ghIntegrations, ".apk")
The functions were removed during refactoring, so I am going to mark this as resolved.

2023-08-03 09:28 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/settings/AdvancedSettingsScreen.kt
> +private fun APIUrlDialog(currentUrl: String, onSubmit: (String?) -> Unit) {
fine ig

2023-08-03 09:34 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BaseBundleDialog.kt
> +inline fun BaseBundleDialog(
Ended up removing the inline because it probably does not make a difference.

2023-08-03 10:22 UTC, CnC-Robert approved these changes

2023-08-03 11:15 UTC, merged