feat: download apps in patcher screen
ReVanced/revanced-manager-compose pull request #73
Opened 2023-07-29 18:45 UTC by CnC-Robert

Download apps in the patcher screen instead of in the version selector screen

Also fixes #56

2023-07-29 20:29 UTC, Axelen123 requested changes

2023-07-29 20:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/patcher/worker/PatcherWorker.kt
> +    private val context: Context,
Use `applicationContext`

2023-07-29 20:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/patcher/worker/PatcherWorker.kt
> +                is SelectedApp.Installed -> File(context.packageManager.getPackageInfo(args.input.packageName, 0).applicationInfo.sourceDir)
Feels like this belongs in `PM`

2023-07-29 20:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/AppLabel.kt
> +    var label by rememberSaveable { mutableStateOf("Loading...") }
This should be a string resource

2023-07-29 20:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/AppLabel.kt
> +        modifier = Modifier.placeholder(visible = label == "Loading...", color = MaterialTheme.colorScheme.inverseOnSurface, shape = RoundedCornerShape(100)).then(modifier),
Maybe make `label` nullable and use `?:` instead of comparing it to a hardcoded value

2023-07-29 20:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/InstallerScreen.kt
> +                                    "${it.first}MB/${it.second}MB",
This would be more readable if you destructured the `Pair`. `first` and `second` seem ambiguous.
Also, maybe just say `MB` once instead of twice?

2023-07-29 20:29 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/InstallerScreen.kt
> +                    progress = it.first / it.second,
Same here. Can you destructure the pair?

2023-07-30 07:32 UTC, PalmDevs commented
insane

2023-07-30 09:33 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/patcher/worker/PatcherWorker.kt
> +                is SelectedApp.Installed -> File(context.packageManager.getPackageInfo(args.input.packageName, 0).applicationInfo.sourceDir)
That requires injecting `PM` just for this tho

2023-07-30 10:09 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/AppLabel.kt
> +        }
Maybe do something like this instead so you don't need three `withContext`s.
```kt
label = withContext(Dispatchers.IO) {
     packageInfo?.appInfo?.loadLabel(context.packageManager)
}?.toString() ?: defaultText
```

2023-07-30 10:28 UTC, Axelen123 approved these changes

2023-07-30 10:29 UTC, merged