feat: make patch bundles selectable
ReVanced/revanced-manager-compose pull request #76
Opened 2023-08-07 00:15 UTC by Tyffhabwe

The patch bundles are now selectable from the dashboard as per the figma

2023-08-07 08:58 UTC, Axelen123 requested changes

2023-08-07 08:58 UTC, Axelen123 commented on app/src/main/res/values/strings.xml
> +    <string name="patches_selected">%s selected</string>
This name seems confusing

2023-08-07 08:58 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/BundlesScreen.kt
> +    }
Composables shouldn't cause side effects like this. Side effects should instead be triggered by event handlers or things like `LaunchedEffect`/`DisposableEffect`.

2023-08-07 08:58 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/BundlesScreen.kt
> +                reAssignCheckBoxTicked = { newCheckBoxValue -> checkBoxTicked = newCheckBoxValue }
Why are there two functions for modifying `checkBoxTicked`?

Can this be renamed to something like `selected`?

2023-08-07 08:58 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/BundlesScreen.kt
> +                sourcesSelectable = sourcesSelectable,
Maybe just `selectable` or `selectionActive`?

2023-08-07 08:58 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/BundlesScreen.kt
> +                },
Can you rename this to give a hint as to how it edits the list?

2023-08-07 08:58 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/BundlesScreen.kt
> +    selectedSources: SnapshotStateList<PatchBundleSource>,
Mutable compose state should not be passed down

2023-08-07 08:58 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +    val selectedSources = remember { mutableStateListOf<PatchBundleSource>() }
This will be lost if you rotate the screen. Move it to the viewmodel to prevent that from happening

2023-09-02 15:36 UTC, Axelen123 requested changes

2023-09-02 15:36 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundleItem.kt
> +    onLongClick: () -> Unit,
Rename this to something like `onSelect()`

2023-09-02 15:36 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                                        },
I don't think you need a callback for this

2023-09-02 15:36 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                                        invertBundleSelectionStatus = { bundleIsNotSelected ->
Rename this to something like `toggleSelection`

2023-09-02 15:36 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                                        sourcesSelectable = sourcesSelectable,
Rename the parameter to `selectable` and the variable to `bundlesSelectable`

2023-09-02 15:36 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                            val sources by vm.sources.collectAsStateWithLifecycle(initialValue = listOf())
You can use `emptyList()` instead of `listOf()`

2023-09-02 15:36 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +    val selectedSources = remember { mutableStateListOf<PatchBundleSource>() }
Still needs to be done

2023-09-02 15:49 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/component/bundle/BundleItem.kt
> +    onLongClick: () -> Unit,
done!

2023-09-02 15:49 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +    val selectedSources = remember { mutableStateListOf<PatchBundleSource>() }
done!

2023-09-02 15:49 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                            val sources by vm.sources.collectAsStateWithLifecycle(initialValue = listOf())
done!

2023-09-02 15:49 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                                        sourcesSelectable = sourcesSelectable,
done!

2023-09-02 15:49 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                                        },
done!

2023-09-02 15:50 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/DashboardScreen.kt
> +                                        invertBundleSelectionStatus = { bundleIsNotSelected ->
done!

2023-09-02 16:41 UTC, Axelen123 approved these changes
Looks good. I will move it to the main repo tomorrow

2023-09-07 09:13 UTC, Axelen123 commented
Closing this because it has been merged in the main repo

2023-09-07 09:13 UTC, closed without merging