feat: store patched apps
ReVanced/revanced-manager-compose pull request #79
Opened 2023-08-09 09:43 UTC by CnC-Robert

TODO:
- [ ] Save patch selection

2023-08-09 11:24 UTC, Axelen123 requested changes

2023-08-09 11:24 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppInfoViewModel.kt
> +        viewModelScope.launch(Dispatchers.Main) {
I believe `viewModelScope` uses `Dispatchers.Main` by default, so I don't think you have to specify it explicitly.

2023-08-09 11:24 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +        }
UI composables ideally shouldn't have "dangerous" side effects simply because you rendered them. I believe this logic would make more sense in a viewmodel.

2023-08-09 11:24 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +    var appInfo: PackageInfo? by rememberSaveable { mutableStateOf(null) }
Is it possible to move this to the viewmodel in order to save space in the bundle?

Should be possible with a `SnapshotStateMap`.

2023-08-09 11:24 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/AppInfoScreen.kt
> +                    trailingContent = { Icon(Icons.Filled.ArrowRight, contentDescription = null) }
Maybe this should have a description that says something like "click to view applied patches" for improved accessibility

2023-08-09 11:24 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/data/room/apps/installed/InstalledApp.kt
> +enum class InstallType(val displayName: String) {
`displayName` should be a string resource. Also, doesn't this need `@Parcelize` and a db converter or does it work without them?

2023-08-16 09:38 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppInfoViewModel.kt
> +        viewModelScope.launch(Dispatchers.Main) {
Nope it uses `Dispatchers.Default` when no dispatcher is specified

2023-08-16 09:50 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +        }
That will require to load all apps twice tho

2023-08-16 09:51 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/data/room/apps/installed/InstalledApp.kt
> +enum class InstallType(val displayName: String) {
Nop `@Parcelize` is not needed for enums apparently

2023-08-16 12:05 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +        }
Nevermind that isn't required

2023-08-16 13:23 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppInfoViewModel.kt
> +        viewModelScope.launch(Dispatchers.Main) {
Are you sure? I was under the assumption that it uses `Main` because coroutines launched by those scopes often want to imteract with UI state. Where did you find out about this?

2023-08-16 13:55 UTC, Axelen123 requested changes

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/data/room/apps/installed/AppliedPatch.kt
> +    @ColumnInfo(name = "bundle_uid") val bundleUid: Int,
Can you rename this to just `bundle` to keep it consistent with the other database entities?

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/data/room/apps/installed/InstalledApp.kt
> +}
This type will become relevant in other parts of the app later, so maybe it should be moved.

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/InstalledAppRepository.kt
> +        }
Change the query so you can insert multiple `AppliedPatch` objects at once. Also, these two database modifications should ideally be done in a transaction.

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/domain/repository/InstalledAppRepository.kt
> +            .groupBy { it.bundleUid }
Room can do this for you with multimap return types.
Check these links or ask me if you want help:
https://github.com/ReVanced/revanced-manager-compose/blob/cd75ac90d9000686c2b1c437ba42c27eff99d5a5/app/src/main/java/app/revanced/manager/data/room/selection/SelectionDao.kt#L21
https://developer.android.com/training/data-storage/room/relationships#multimap

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/AppInfoScreen.kt
> +                                viewModel.appliedPatches?.values?.sumOf { it.size } ?: 0,
Can you assign this to a variable so you don't have to duplicate it?

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +    ) {
Its possible to just use a single LazyColumn for everything.
You can define a single `item { }` and early return from the `LazyColumn` lambda if `installedApps` is null or empty.

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppInfoViewModel.kt
> +        )
You need to unregister this in `onCleared`

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/InstalledAppsViewModel.kt
> +                it.forEach { installedApp ->
Can you extract the `forEach` to a function in order to reduce nesting? Makes the code easier to read

2023-08-16 13:55 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/VersionSelectorViewModel.kt
> +                withContext(Dispatchers.Default) {
The `await()`s don't block, so I don't think you need the `withContext` here

2023-08-16 13:59 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/data/room/apps/installed/InstalledApp.kt
> +}
To where? We can also move it later tho

2023-08-16 14:00 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppInfoViewModel.kt
> +        viewModelScope.launch(Dispatchers.Main) {
![image](https://github.com/ReVanced/revanced-manager-compose/assets/72943079/4f16d161-caba-4a84-9c8b-3e1e648a390d)

2023-08-16 14:02 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +    ) {
Then i cant center the loading indicator and the "No patched apps" text

2023-08-16 14:12 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +    ) {
Why wouldn't you? Can't you specify alignment and arrangement in a lazycolumn?

2023-08-17 08:52 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/viewmodel/AppInfoViewModel.kt
> +        viewModelScope.launch(Dispatchers.Main) {
Yep you're right it is on main

2023-08-17 11:01 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/InstalledAppsScreen.kt
> +    ) {
Yeah nevermind i thought it wouldn't work

2023-08-17 14:03 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/data/room/apps/installed/InstalledApp.kt
> +}
Hmm, true

2023-08-17 14:26 UTC, Axelen123 requested changes

2023-08-17 14:26 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/data/room/apps/installed/InstalledAppDao.kt
> +    suspend fun insertApp(installedApp: InstalledApp)
Might be a little confusing to have two functions with slightly different names. An overload probably makes more sense (simply give both of them the exact same name)

2023-08-17 14:26 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/AppInfoScreen.kt
> +    onPatchClick: (packageName: String, patchesSelection: PatchesSelection) -> Unit,
We don't give lambda parameters names in the rest of the codebase. Its up to you if you want to remove them or not. Keep them if you believe it makes the code more clear

2023-08-17 14:26 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/viewmodel/InstalledAppsViewModel.kt
> +            apps.collectEach { installedApp ->
All flow operators *before* a `flowOn` will use the context in the `flowOn`, but the operators *after* `flowOn` won't.
This means you can remove the `Dispatchers.IO` parameter from `launch` and the `withContext(Dispatchers.Main)`.

2023-08-17 14:31 UTC, CnC-Robert commented on app/src/main/java/app/revanced/manager/ui/screen/AppInfoScreen.kt
> +    onPatchClick: (packageName: String, patchesSelection: PatchesSelection) -> Unit,
It doesn't hurt to keep them

2023-08-17 15:33 UTC, Axelen123 approved these changes

2023-08-17 15:42 UTC, merged