feat: more info for the select from application screen
ReVanced/revanced-manager-compose pull request #81
Opened 2023-08-14 01:54 UTC by Tyffhabwe

2023-08-14 09:14 UTC, Axelen123 requested changes

2023-08-14 09:14 UTC, Axelen123 commented on app/src/main/java/app/revanced/manager/ui/screen/AppSelectorScreen.kt
> +                        )
What is this for?

2023-08-14 09:14 UTC, Axelen123 commented on app/src/main/res/values/strings.xml
> +    <string name="select_an_installation_file">Select an installation file using file picker</string>
Can you rename this to `select_from_storage_description` to keep it consistent?

2023-08-20 06:34 UTC, Tyffhabwe commented on app/src/main/java/app/revanced/manager/ui/screen/AppSelectorScreen.kt
> +                        )
App selector screen
![image](https://github.com/ReVanced/revanced-manager-compose/assets/20930072/4cabffa3-584b-464c-b4fd-a44674a153e0)

2023-08-22 09:39 UTC, Tyffhabwe commented
![Screenshot_2023-08-22-21-34-11-03_a7c8ff5d38679aafe3a21eaf88d67b8c](https://github.com/ReVanced/revanced-manager-compose/assets/20930072/1dd7cde4-9124-474a-99c1-505f38a9c710)
![Screenshot_2023-08-22-21-34-17-51_a7c8ff5d38679aafe3a21eaf88d67b8c](https://github.com/ReVanced/revanced-manager-compose/assets/20930072/c2bdec7c-0f92-499f-835f-bd42f40214d9)

2023-08-22 12:39 UTC, oSumAtrIX reviewed
A lot of formatting changes have been made. Please make sure only to make necessary changes next time and formatting changes separately to simplify the review.

2023-08-22 12:39 UTC, oSumAtrIX commented on app/src/main/res/values/strings.xml
> +    <string name="select_from_storage_description">Select an installation file using file picker</string>
```suggestion
    <string name="select_from_storage_description">Select an APK file from storage using file picker</string>
```

2023-08-23 18:05 UTC, Axelen123 approved these changes

2023-08-23 18:05 UTC, merged