docs: added move notice
ReVanced/revanced-manager-compose pull request #93
Opened 2023-09-10 17:23 UTC by BenjaminHalko

We should let people know that development has moved to the ReVanced Manager repo.

2023-09-10 17:24 UTC, Axelen123 requested changes

2023-09-10 17:24 UTC, Axelen123 commented on README.md
> +All future development on the ReVanced Manager Compose has been moved to the [revanced-manager](https://github.com/ReVanced/revanced-manager) repository.
The branch should be mentioned as well so people can more easily find it

2023-09-10 18:11 UTC, oSumAtrIX commented on README.md
> +# ⚠️ MOVING NOTICE ⚠️
Only one heading is allowed. Move this under the title and use "##"

2023-09-10 18:23 UTC, oSumAtrIX commented on README.md
> +All future development on the ReVanced Manager Compose has been moved to the [revanced-manager](https://github.com/ReVanced/revanced-manager) repository.
i think it makes more sense for this repo to redirect to the other, then the other can specify in which branch what happens

2023-09-12 01:36 UTC, BenjaminHalko commented
@oSumAtrIX Formatting has been fixed

2023-09-12 02:28 UTC, oSumAtrIX commented on README.md
> +## ⚠️ MOVING NOTICE ⚠️
```suggestion
## Notice
```

2023-09-12 02:29 UTC, oSumAtrIX commented on README.md
> +All future development on the Compose rewrite of ReVanced Manager has been moved to the [compose-dev](https://github.com/ReVanced/revanced-manager/tree/compose-dev) branch in the [revanced-manager](h
```suggestion
Development is continued in the [ReVanced Manager](https://github.com/ReVanced/revanced-manager) repository.
```

2023-09-12 02:29 UTC, oSumAtrIX requested changes
The emojis is unconventional in this readme.
The branch should be unspecified because it will change later and can be specified in the readme of the revanced manager repository but not this repository, because it will be archived.

2023-09-12 04:01 UTC, BenjaminHalko commented
@oSumAtrIX done

2023-09-12 04:06 UTC, BenjaminHalko commented
@oSumAtrIX done

2023-09-14 01:49 UTC, oSumAtrIX commented on README.md
> +## MOVING NOTICE
```suggestion
## Moved development
```

2023-09-14 01:50 UTC, oSumAtrIX approved these changes

2023-09-15 16:29 UTC, merged